# Generated by Django 3.0.2 on 2020-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
        ('kullanici', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='takimlar',
            field=models.ManyToManyField(related_name='takimlar', to='takim.Takim'),
        ),
    ]
