# Generated by Django 3.0.2 on 2020-01-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0002_kullanici_takimlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kullanici',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
