# Generated by Django 3.0.2 on 2020-01-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0002_auto_20200129_0326'),
        ('auth', '0011_update_proxy_permissions'),
        ('kullanici', '0004_auto_20200129_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='gruplar', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='takimlar',
            field=models.ManyToManyField(blank=True, null=True, related_name='takimlar', to='takim.Takim'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='izinler', to='auth.Permission'),
        ),
    ]
