# Generated by Django 3.0.2 on 2020-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0005_auto_20200129_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
