# Generated by Django 3.0.2 on 2020-01-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0006_kullanici_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='mail',
        ),
    ]
