# Generated by Django 3.0.2 on 2020-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0007_remove_kullanici_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='lokasyon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
