# Generated by Django 3.0.2 on 2020-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0008_auto_20200130_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='password_reset_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
