# Generated by Django 3.0.2 on 2020-02-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0009_kullanici_password_reset_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanici',
            old_name='bio',
            new_name='title',
        ),
    ]
