# Generated by Django 3.0.2 on 2020-02-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0006_gorev_sahip'),
        ('kullanici', '0010_auto_20200203_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='gorevler',
            field=models.ManyToManyField(null=True, related_name='gorevler', to='gorev.Gorev'),
        ),
    ]
