# Generated by Django 3.0.2 on 2020-02-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0012_auto_20200203_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='invite_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
