# Generated by Django 3.0.2 on 2020-02-09 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gorev', '0005_remove_gorev_gorev_grubu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivite_tipi', models.CharField(choices=[('silme', 'Silme'), ('guncelleme', 'Güncelleme'), ('ekleme', 'Ekleme')], max_length=20)),
                ('aktivite', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gorev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteler', to='gorev.Gorev')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteler', to=settings.AUTH_USER_MODEL)),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteler', to='proje.Proje')),
            ],
        ),
    ]
