# Generated by Django 3.0.2 on 2020-02-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivite', '0002_auto_20200209_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktivite',
            options={'verbose_name': 'Aktivite', 'verbose_name_plural': 'Aktiviteler'},
        ),
        migrations.AlterField(
            model_name='aktivite',
            name='aktivite_tipi',
            field=models.CharField(choices=[('silme', 'Silindi'), ('guncelleme', 'Güncellendi'), ('olusturma', 'Oluşturuldu'), ('ekleme', 'Eklendi')], max_length=20),
        ),
    ]
