# Generated by Django 3.0.2 on 2020-01-29 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('baslama_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Not',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gorev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notlar', to='gorev.Gorev')),
                ('yazar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Islem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('islem_sureci', models.CharField(choices=[('bitti', 'İşlem Bitti'), ('devam', 'İşlem Devam Ediyor')], max_length=5)),
                ('gorev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islemler', to='gorev.Gorev')),
            ],
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('tip', models.CharField(max_length=255)),
                ('dosya', models.FileField(upload_to='gorevler/dosyalar/')),
                ('gorev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosyalar', to='gorev.Gorev')),
            ],
        ),
    ]
