# Generated by Django 3.0.2 on 2020-01-29 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
        ('gorev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorev',
            name='proje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to='proje.Proje'),
        ),
    ]
