# Generated by Django 3.0.2 on 2020-01-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0002_gorev_proje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosya',
            options={'verbose_name': 'Dosya', 'verbose_name_plural': 'Dosyalar'},
        ),
        migrations.AlterModelOptions(
            name='gorev',
            options={'verbose_name': 'Görev', 'verbose_name_plural': 'Görevler'},
        ),
        migrations.AlterModelOptions(
            name='islem',
            options={'verbose_name': 'İşlem', 'verbose_name_plural': 'İşlemler'},
        ),
        migrations.AlterModelOptions(
            name='not',
            options={'verbose_name': 'Not', 'verbose_name_plural': 'Notlar'},
        ),
    ]
