# Generated by Django 3.0.2 on 2020-01-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0003_auto_20200129_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islem',
            name='islem_sureci',
            field=models.CharField(choices=[('bitti', 'İşlem Bitti'), ('devam', 'İşlem Devam Ediyor')], default='devam', max_length=5),
        ),
    ]
