# Generated by Django 3.0.2 on 2020-02-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0003_islem_eklenme_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorev',
            name='gorev_durum',
            field=models.CharField(choices=[('bitti', 'Görev Bitti'), ('devam', 'Görev Devam Ediyor'), ('yapilacak', 'Görev Yapılmalı')], default='yapilacak', max_length=11),
        ),
    ]
