# Generated by Django 3.0.2 on 2020-02-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0004_auto_20200208_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorev',
            name='gorev_grubu',
        ),
    ]
