# Generated by Django 3.0.2 on 2020-02-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0006_gorevdosya_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevdosya',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
