# Generated by Django 3.0.2 on 2020-02-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gorev', '0006_gorev_sahip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='not',
            old_name='yazar',
            new_name='kullanici',
        ),
        migrations.RemoveField(
            model_name='dosya',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='dosya',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='gorev',
            name='sahip',
        ),
        migrations.AddField(
            model_name='gorev',
            name='kullanici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kullanici', to=settings.AUTH_USER_MODEL),
        ),
    ]
