# Generated by Django 3.0.2 on 2020-02-13 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0006_remove_proje_gizlilik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gorev', '0007_gorevdosya_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorev',
            name='proje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='proje.Proje'),
        ),
        migrations.AlterField(
            model_name='gorevdosya',
            name='gorev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='gorev.Gorev'),
        ),
        migrations.AlterField(
            model_name='islem',
            name='gorev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='islemler', to='gorev.Gorev'),
        ),
        migrations.AlterField(
            model_name='not',
            name='gorev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='gorev.Gorev'),
        ),
        migrations.AlterField(
            model_name='not',
            name='kullanici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
