# Generated by Django 3.0.2 on 2020-02-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0007_auto_20200203_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gorev',
            old_name='kullanici',
            new_name='sahip',
        ),
    ]
