# Generated by Django 3.0.2 on 2020-02-03 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gorev', '0009_auto_20200203_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorev',
            name='sahip',
        ),
        migrations.AddField(
            model_name='gorev',
            name='kullanicilar',
            field=models.ManyToManyField(null=True, related_name='gorevler', to=settings.AUTH_USER_MODEL),
        ),
    ]
