# Generated by Django 3.0.2 on 2020-02-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0010_auto_20200203_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gorev',
            old_name='kullanicilar',
            new_name='uyeler',
        ),
    ]
