# Generated by Django 3.0.2 on 2020-02-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0011_auto_20200203_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorev',
            name='gorev_durum',
            field=models.CharField(choices=[('bitti', 'Görev Bitti'), ('devam', 'Görev Devam Ediyor')], default='devam', max_length=5),
        ),
    ]
