# Generated by Django 3.0.2 on 2020-01-29 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('baslama_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('gizlilik', models.CharField(choices=[('herkese_acik', 'Herkese Açık'), ('takim_uyeleri', 'Sadece Takım Üyeleri'), ('sadece_ben', 'Sadece Ben')], max_length=25)),
                ('takim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to='takim.Takim')),
            ],
        ),
    ]
