# Generated by Django 3.0.2 on 2020-02-06 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('baslama_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('gizlilik', models.CharField(choices=[('herkese_acik', 'Herkese Açık'), ('takim_uyeleri', 'Sadece Takım Üyeleri'), ('sadece_ben', 'Sadece Ben')], max_length=25)),
                ('slug', models.SlugField(blank=True)),
                ('takim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to='takim.Takim')),
                ('uyeler', models.ManyToManyField(null=True, related_name='projeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
        migrations.CreateModel(
            name='ProjeDosya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='projeler/dosyalar/')),
                ('ad', models.CharField(blank=True, max_length=255)),
                ('proje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosyalar', to='proje.Proje')),
                ('yukleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proje_dosyalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proje Dosyası',
                'verbose_name_plural': 'Proje Dosyaları',
            },
        ),
    ]
