# Generated by Django 3.0.2 on 2020-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projedosya',
            name='content_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
