# Generated by Django 3.0.2 on 2020-02-03 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proje', '0002_auto_20200129_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='sahip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to=settings.AUTH_USER_MODEL),
        ),
    ]
