# Generated by Django 3.0.2 on 2020-02-03 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proje', '0003_proje_sahip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proje',
            name='sahip',
        ),
        migrations.AddField(
            model_name='proje',
            name='uyeler',
            field=models.ManyToManyField(null=True, related_name='projeler', to=settings.AUTH_USER_MODEL),
        ),
    ]
