# Generated by Django 3.0.2 on 2020-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0003_projedosya_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='projedosya',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
