# Generated by Django 3.0.2 on 2020-02-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0004_projedosya_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projedosya',
            name='path',
        ),
    ]
