# Generated by Django 3.0.2 on 2020-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0004_auto_20200203_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='slug',
            field=models.SlugField(default='-ds-ds'),
            preserve_default=False,
        ),
    ]
