# Generated by Django 3.0.2 on 2020-02-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0005_remove_projedosya_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proje',
            name='gizlilik',
        ),
    ]
