# Generated by Django 3.0.2 on 2020-02-13 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
        ('proje', '0006_remove_proje_gizlilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='takim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeler', to='takim.Takim'),
        ),
        migrations.AlterField(
            model_name='projedosya',
            name='proje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='proje.Proje'),
        ),
    ]
