# Generated by Django 3.0.2 on 2020-02-06 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sahip_oldugu_takimlar', to=settings.AUTH_USER_MODEL)),
                ('uyeler', models.ManyToManyField(null=True, related_name='takimlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
            },
        ),
    ]
