# Generated by Django 3.0.2 on 2020-01-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takim',
            options={'verbose_name': 'Takım', 'verbose_name_plural': 'Takımlar'},
        ),
    ]
