# Generated by Django 3.0.2 on 2020-02-03 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takim', '0002_auto_20200129_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='takim',
            name='uyeler',
            field=models.ManyToManyField(related_name='uyeler', to=settings.AUTH_USER_MODEL),
        ),
    ]
