# Generated by Django 3.0.2 on 2020-02-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0005_auto_20200203_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='takim',
            name='slug',
            field=models.SlugField(default='as-as'),
            preserve_default=False,
        ),
    ]
