# Generated by Django 3.0.2 on 2020-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0006_takim_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takim',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
