# Generated by Django 3.0.2 on 2020-02-03 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takim', '0007_auto_20200203_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='takim',
            name='sahip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sahip_oldugu_takimlar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
